### ISSUE TITLE
Reusable code

### ISSUE THREAD

**Issue by humblewebdev** [danielpolk/Project-1#36]
https://github.com/danielpolk/Project-1/blob/51824412e0ef9f4c428ccb0f3adf67906b3a2b0b/js/APIs.html#L126

Instead of making a function that surrounds a click event. Create a function you can call in the closure.  This would allow for you to reuse functionality.

**Comment by markpython86** [comment]
> [Project-1/js/APIs.html](https://github.com/danielpolk/Project-1/blob/51824412e0ef9f4c428ccb0f3adf67906b3a2b0b/js/APIs.html#L126)
> 
> Line 126 in [5182441](/danielpolk/Project-1/commit/51824412e0ef9f4c428ccb0f3adf67906b3a2b0b)
> 
>              $("#submit").on("click", function (e) { 
> Instead of making a function that surrounds a click event. Create a function you can call in the closure. This would allow for you to reuse functionality.

That's great advice. will make sure to do that in the future. Thank you
